wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0rc1
    cli_version: 0.17.4
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1729689066
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.0rc1
      5: 0.17.4
      8:
      - 1
      - 5
      13: linux-x86_64
    viz:
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
      summary_metrics:
        id: wandb/metrics/v1
        historyFieldSettings:
          x-axis: _step
          key: summary_metrics
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      calibration_curve:
        id: wandb/calibration/v1
        historyFieldSettings:
          x-axis: _step
          key: calibration_curve
    visualize:
      roc:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: fpr
            y: tpr
            class: class
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: roc_table
                fields: []
      precision_recall:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: recall
            y: precision
            class: class
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: precision_recall_table
                fields: []
